replicaCount: 2

image:
  repository: sisi1234/zomota-project
  tag: latest
  pullPolicy: IfNotPresent
  containerPort: 3000

resources:
  limits:
    cpu: 150m
    memory: 250Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000
